before_script:
  - apk add --update bash git ruby ruby-json python curl emacs 1>/dev/null
  - export PATH=~/.cask/bin:$PATH
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python &>/dev/null
  - cask

build:
 stage: build
 script:
   - cask build

warnings:
 stage: test
 script:
   - cask build 2>&1 | tee /tmp/build
   - "# If :Warning: was displayed above, this test fails"
   - "[ $(grep ':Warning:' /tmp/build | wc -l) -gt 0 ] && return 1 || return 0"

ert-runner:
 stage: test
 script:
   - cask exec ert-runner
