image: bandresen/alpine-emacs

before_script:
  - cask list
  - cask --dev --verbose
  
after_script:
  - emacs --version | head -n 1

build:
 stage: build
 artifacts:
   paths:
     - .cask/
     - build.log
   expire_in: 5 minutes
 script:
   - cask build 2>&1 | tee build.log
   - "# If :Error: is found in build.log, this test fails"
   - "[ $(grep ':Error:' build.log | wc -l) -eq 0 ]"

warnings:
 stage: test
 dependencies: [build]
 script:
   - cat build.log
   - "# If :Warning: is found in build.log, this test fails"
   - "[ $(grep ':Warning:' build.log | wc -l) -eq 0 ]"

ert-runner:
 stage: test
 dependencies: [build]
 script:
   - cask exec ert-runner --reporter ert+duration --verbose
